import injectJsError from './lib/jsError';
import injectXhrError from './lib/xhr';
import injectFetch from './lib/fetch';
import blankScreen from './lib/blankScreen';
import timing from './lib/timing';
injectJsError();
injectXhrError();
injectFetch();
// blankScreen();
// timing();
